---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jameslendrem.
--- DateTime: 09/11/2023 18:23
---

local pd <const> = playdate
local gfx <const> = pd.graphics

class('Bullet').extends(gfx.sprite)

function Bullet:init(x, y, speed)

    local bulletSize = 4;
    local bulletImage = gfx.image.new(bulletSize * 2, bulletSize * 2)

    --- Push context draws directly to the context provided in this case
    --- the image, not the screen.
    gfx.pushContext(bulletImage)
        --- Okay, I see this dodgy identation.. not sure if I like.
        gfx.drawCircleAtPoint(bulletSize, bulletSize, bulletSize)
    gfx.popContext()
    self:add()
    self:setImage(bulletImage)

    --- Okay, said wil explain but guess...
    --- creates a rect at 0, 0 relative to image and of the size of the image
    --- which will be bulletSize * 2 which can detect other collision rects
    self:setCollideRect(0, 0, self:getSize())
    self.speed = speed
    self:moveTo(x, y)
    self:add()
end

function Bullet:update()

    --- So what happens first? I add curly braces in lua or start forgetting to add them
    --- in js?
    local actualX, actualY, collisions, length = self:moveWithCollisions(self.x + self.speed, self.y);

    if (length > 0) then
        for i, collision in pairs(collisions) do
            local collidedObject = collision["other"]
            if collidedObject:isa(Enemy) then

                local enemy = collidedObject;
                enemy.health = enemy.health - 1;

                if (enemy.health == 0) then
                    collidedObject:remove()
                    incrementScore()
                    setShakeAmount(5)
                end

            end
        end
        self:remove()
    elseif actualX > 400 then
        self:remove()
    end
end