---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jameslendrem.
--- DateTime: 09/11/2023 10:56
---

import "CoreLibs/object"
import "CoreLibs/graphics"
import "CoreLibs/sprites"
import "CoreLibs/timer"
import "player"
import "enemySpawner"
import "scoreDisplay"

--- Potential performance inprovement with const
--- local because lua is weird and everything is in global scope without it :/
local pd <const> = playdate
local gfx <const> = pd.graphics
local player <const> = Player(30, 120)
createScoreDisplay();
startSpawner()

function resetGame()
   resetScore()
   clearEnemies()
   stopSpawner()
   startSpawner()
end

function playdate.update()
   --- Main Game Loop

   --- update all sprites
   gfx.sprite.update()

   --- update all timers
   pd.timer.updateTimers()


end