---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jameslendrem.
--- DateTime: 09/11/2023 10:56
---

import "CoreLibs/object"
import "CoreLibs/graphics"
import "CoreLibs/sprites"
import "CoreLibs/timer"
import "player"
import "enemySpawner"
import "scoreDisplay"
import "screenShake"

--- Potential performance inprovement with const
--- local because lua is weird and everything is in global scope without it :/
local pd <const> = playdate
local gfx <const> = pd.graphics
local player <const> = Player(30, 120)
local screenShakeSprite = ScreenShake()
createScoreDisplay();
startSpawner()

function setShakeAmount(amount)
   screenShakeSprite:setShakeAmount(amount)
end

function resetGame()
   resetScore()
   clearEnemies()
   stopSpawner()
   startSpawner()
   setShakeAmount(10)
end

function playdate.update()
   --- Main Game Loop

   --- update all sprites
   gfx.sprite.update()

   --- update all timers
   pd.timer.updateTimers()


end